# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p2pdemo_mainWindow.ui'
#
# Created: Sat Apr 27 18:46:17 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_p2p_mainWindow(object):
    def setupUi(self, p2p_mainWindow):
        p2p_mainWindow.setObjectName(_fromUtf8("p2p_mainWindow"))
        p2p_mainWindow.resize(697, 721)
        self.centralwidget = QtGui.QWidget(p2p_mainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0, 30, 697, 668))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.CentralTabview = QtGui.QTabWidget(self.centralwidget)
        self.CentralTabview.setMinimumSize(QtCore.QSize(668, 582))
        self.CentralTabview.setObjectName(_fromUtf8("CentralTabview"))
        self.conf_tab = QtGui.QWidget()
        self.conf_tab.setGeometry(QtCore.QRect(0, 0, 664, 622))
        self.conf_tab.setObjectName(_fromUtf8("conf_tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.conf_tab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.line = QtGui.QFrame(self.conf_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_4 = QtGui.QLabel(self.conf_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.conf_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.self_ip = QtGui.QLineEdit(self.conf_tab)
        self.self_ip.setEnabled(True)
        self.self_ip.setFrame(True)
        self.self_ip.setReadOnly(True)
        self.self_ip.setObjectName(_fromUtf8("self_ip"))
        self.horizontalLayout_2.addWidget(self.self_ip)
        self.label_8 = QtGui.QLabel(self.conf_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.self_port = QtGui.QLineEdit(self.conf_tab)
        self.self_port.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.self_port.sizePolicy().hasHeightForWidth())
        self.self_port.setSizePolicy(sizePolicy)
        self.self_port.setMinimumSize(QtCore.QSize(50, 0))
        self.self_port.setStyleSheet(_fromUtf8(""))
        self.self_port.setReadOnly(True)
        self.self_port.setObjectName(_fromUtf8("self_port"))
        self.horizontalLayout_2.addWidget(self.self_port)
        self.label_5 = QtGui.QLabel(self.conf_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_2.addWidget(self.label_5)
        self.pub_ip = QtGui.QLineEdit(self.conf_tab)
        self.pub_ip.setEnabled(True)
        self.pub_ip.setReadOnly(True)
        self.pub_ip.setObjectName(_fromUtf8("pub_ip"))
        self.horizontalLayout_2.addWidget(self.pub_ip)
        self.label_3 = QtGui.QLabel(self.conf_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.self_as = QtGui.QLineEdit(self.conf_tab)
        self.self_as.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.self_as.sizePolicy().hasHeightForWidth())
        self.self_as.setSizePolicy(sizePolicy)
        self.self_as.setMinimumSize(QtCore.QSize(50, 0))
        self.self_as.setMaximumSize(QtCore.QSize(300, 16777215))
        self.self_as.setReadOnly(True)
        self.self_as.setObjectName(_fromUtf8("self_as"))
        self.horizontalLayout_2.addWidget(self.self_as)
        self.label_2 = QtGui.QLabel(self.conf_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.self_cc = QtGui.QLineEdit(self.conf_tab)
        self.self_cc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.self_cc.sizePolicy().hasHeightForWidth())
        self.self_cc.setSizePolicy(sizePolicy)
        self.self_cc.setMinimumSize(QtCore.QSize(30, 0))
        self.self_cc.setMaximumSize(QtCore.QSize(200, 16777214))
        self.self_cc.setReadOnly(True)
        self.self_cc.setObjectName(_fromUtf8("self_cc"))
        self.horizontalLayout_2.addWidget(self.self_cc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.port_table = QtGui.QTableWidget(self.conf_tab)
        self.port_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.port_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.port_table.setTabKeyNavigation(True)
        self.port_table.setProperty("showDropIndicator", False)
        self.port_table.setDragDropOverwriteMode(False)
        self.port_table.setAlternatingRowColors(True)
        self.port_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.port_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.port_table.setShowGrid(False)
        self.port_table.setGridStyle(QtCore.Qt.SolidLine)
        self.port_table.setWordWrap(True)
        self.port_table.setCornerButtonEnabled(False)
        self.port_table.setRowCount(0)
        self.port_table.setColumnCount(4)
        self.port_table.setObjectName(_fromUtf8("port_table"))
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.port_table)
        self.snapshotButton = QtGui.QPushButton(self.conf_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.snapshotButton.sizePolicy().hasHeightForWidth())
        self.snapshotButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/Snapshot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snapshotButton.setIcon(icon)
        self.snapshotButton.setObjectName(_fromUtf8("snapshotButton"))
        self.verticalLayout.addWidget(self.snapshotButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.CentralTabview.addTab(self.conf_tab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.CentralTabview)
        p2p_mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(p2p_mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        p2p_mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(p2p_mainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0, 698, 697, 23))
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        p2p_mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(p2p_mainWindow)
        self.CentralTabview.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(p2p_mainWindow)

    def retranslateUi(self, p2p_mainWindow):
        p2p_mainWindow.setWindowTitle(_translate("p2p_mainWindow", "P2PGauge", None))
        self.label_4.setText(_translate("p2p_mainWindow", "Monitored socket", None))
        self.label.setText(_translate("p2p_mainWindow", "IP ", None))
        self.label_8.setText(_translate("p2p_mainWindow", "Port", None))
        self.label_5.setText(_translate("p2p_mainWindow", "Pub IP ", None))
        self.label_3.setText(_translate("p2p_mainWindow", "AS", None))
        self.label_2.setText(_translate("p2p_mainWindow", "CC", None))
        self.port_table.setSortingEnabled(False)
        item = self.port_table.horizontalHeaderItem(0)
        item.setText(_translate("p2p_mainWindow", "Port", None))
        item = self.port_table.horizontalHeaderItem(1)
        item.setText(_translate("p2p_mainWindow", "Packets", None))
        item = self.port_table.horizontalHeaderItem(2)
        item.setText(_translate("p2p_mainWindow", "Bytes", None))
        item = self.port_table.horizontalHeaderItem(3)
        item.setText(_translate("p2p_mainWindow", "Rate (Kb/s)", None))
        self.snapshotButton.setText(_translate("p2p_mainWindow", "Snapshot", None))
        self.CentralTabview.setTabText(self.CentralTabview.indexOf(self.conf_tab), _translate("p2p_mainWindow", "demo.conf", None))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    p2p_mainWindow = QtGui.QMainWindow()
    ui = Ui_p2p_mainWindow()
    ui.setupUi(p2p_mainWindow)
    p2p_mainWindow.show()
    sys.exit(app.exec_())

