# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'P2PDemoTabView.ui'
#
# Created: Wed May 27 17:38:39 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_p2p_demo(object):
    def setupUi(self, p2p_demo):
        p2p_demo.setObjectName("p2p_demo")
        p2p_demo.resize(686, 716)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(p2p_demo.sizePolicy().hasHeightForWidth())
        p2p_demo.setSizePolicy(sizePolicy)
        p2p_demo.setMinimumSize(QtCore.QSize(686, 716))
        self.horizontalLayout = QtGui.QHBoxLayout(p2p_demo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CentralTabview = QtGui.QTabWidget(p2p_demo)
        self.CentralTabview.setMinimumSize(QtCore.QSize(668, 582))
        self.CentralTabview.setObjectName("CentralTabview")
        self.conf_tab = QtGui.QWidget()
        self.conf_tab.setGeometry(QtCore.QRect(0, 0, 664, 670))
        self.conf_tab.setObjectName("conf_tab")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.conf_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.line = QtGui.QFrame(self.conf_tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtGui.QLabel(self.conf_tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.conf_tab)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.self_ip = QtGui.QLineEdit(self.conf_tab)
        self.self_ip.setEnabled(True)
        self.self_ip.setFrame(True)
        self.self_ip.setReadOnly(True)
        self.self_ip.setObjectName("self_ip")
        self.horizontalLayout_2.addWidget(self.self_ip)
        self.label_8 = QtGui.QLabel(self.conf_tab)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.self_port = QtGui.QLineEdit(self.conf_tab)
        self.self_port.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.self_port.sizePolicy().hasHeightForWidth())
        self.self_port.setSizePolicy(sizePolicy)
        self.self_port.setMinimumSize(QtCore.QSize(50, 0))
        self.self_port.setReadOnly(True)
        self.self_port.setObjectName("self_port")
        self.horizontalLayout_2.addWidget(self.self_port)
        self.label_5 = QtGui.QLabel(self.conf_tab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.pub_ip = QtGui.QLineEdit(self.conf_tab)
        self.pub_ip.setEnabled(True)
        self.pub_ip.setReadOnly(True)
        self.pub_ip.setObjectName("pub_ip")
        self.horizontalLayout_2.addWidget(self.pub_ip)
        self.label_3 = QtGui.QLabel(self.conf_tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.self_as = QtGui.QLineEdit(self.conf_tab)
        self.self_as.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.self_as.sizePolicy().hasHeightForWidth())
        self.self_as.setSizePolicy(sizePolicy)
        self.self_as.setMinimumSize(QtCore.QSize(50, 0))
        self.self_as.setMaximumSize(QtCore.QSize(300, 16777215))
        self.self_as.setReadOnly(True)
        self.self_as.setObjectName("self_as")
        self.horizontalLayout_2.addWidget(self.self_as)
        self.label_2 = QtGui.QLabel(self.conf_tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.self_cc = QtGui.QLineEdit(self.conf_tab)
        self.self_cc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.self_cc.sizePolicy().hasHeightForWidth())
        self.self_cc.setSizePolicy(sizePolicy)
        self.self_cc.setMinimumSize(QtCore.QSize(30, 0))
        self.self_cc.setMaximumSize(QtCore.QSize(200, 16777214))
        self.self_cc.setReadOnly(True)
        self.self_cc.setObjectName("self_cc")
        self.horizontalLayout_2.addWidget(self.self_cc)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.port_table = QtGui.QTableWidget(self.conf_tab)
        self.port_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.port_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.port_table.setTabKeyNavigation(True)
        self.port_table.setProperty("showDropIndicator", QtCore.QVariant(False))
        self.port_table.setDragDropOverwriteMode(False)
        self.port_table.setAlternatingRowColors(True)
        self.port_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.port_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.port_table.setShowGrid(False)
        self.port_table.setGridStyle(QtCore.Qt.SolidLine)
        self.port_table.setWordWrap(True)
        self.port_table.setCornerButtonEnabled(False)
        self.port_table.setRowCount(0)
        self.port_table.setColumnCount(4)
        self.port_table.setObjectName("port_table")
        self.port_table.setColumnCount(4)
        self.port_table.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.port_table.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.port_table)
        self.snapshotButton = QtGui.QPushButton(self.conf_tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Snapshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snapshotButton.setIcon(icon)
        self.snapshotButton.setObjectName("snapshotButton")
        self.verticalLayout.addWidget(self.snapshotButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.CentralTabview.addTab(self.conf_tab, "")
        self.horizontalLayout.addWidget(self.CentralTabview)

        self.retranslateUi(p2p_demo)
        self.CentralTabview.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(p2p_demo)

    def retranslateUi(self, p2p_demo):
        p2p_demo.setWindowTitle(QtGui.QApplication.translate("p2p_demo", "P2PGauge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("p2p_demo", "Monitored socket", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("p2p_demo", "IP ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("p2p_demo", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("p2p_demo", "Pub IP ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("p2p_demo", "AS", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("p2p_demo", "CC", None, QtGui.QApplication.UnicodeUTF8))
        self.port_table.setSortingEnabled(False)
        self.port_table.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("p2p_demo", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.port_table.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("p2p_demo", "Packets", None, QtGui.QApplication.UnicodeUTF8))
        self.port_table.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("p2p_demo", "Bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.port_table.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("p2p_demo", "Rate (Kb/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.snapshotButton.setText(QtGui.QApplication.translate("p2p_demo", "Snapshot", None, QtGui.QApplication.UnicodeUTF8))
        self.CentralTabview.setTabText(self.CentralTabview.indexOf(self.conf_tab), QtGui.QApplication.translate("p2p_demo", "demo.conf", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    p2p_demo = QtGui.QWidget()
    ui = Ui_p2p_demo()
    ui.setupUi(p2p_demo)
    p2p_demo.show()
    sys.exit(app.exec_())

